export const POKEMON_GAME_LIST = [
    'Red 🔴',
    'Blue 🔵',
    'Yellow 🟡',
    'Gold 🥇',
    'Silver 🥈',
    'Crystal 🔮',
    'Ruby 🔶',
    'Sapphire 🔷',
    'Emerald 🟢',
    'FireRed 🔥',
    'LeafGreen 🍃',
    'Diamond 💎',
    'Pearl 🦪',
    'Platinum 💿',
    'HeartGold 💛',
    'SoulSilver 💙',
    'Black ⚫',
    'White ⚪',
    'Black 2 🔳',
    'White 2 🔲',
    'X ❌',
    'Y ✅',
    'Omega-Ruby Ω',
    'Alpha-Sapphire α',
    'Sun 🔅',
    'Moon 🌙',
    'Ultra-Sun 🌞',
    'Ultra-Moon 🌕',
    'Sword ⚔️',
    'Shield 🛡'
]

